### PR TITLE
Disallow blocking=render in rel preload & modulepreload

### PR DESCRIPTION
**Pull request by NiedziolkaMichal**
[#8621](https://github.com/whatwg/html/pull/8621)

### CODE REVIEW

**Review by sideshowbarker — COMMENTED** [review]
What’s the context for this change? At https://html.spec.whatwg.org/multipage/semantics.html#the-link-element:blocking-attribute the current spec says:

> The blocking attribute is a [blocking attribute](https://html.spec.whatwg.org/multipage/urls-and-fetching.html#blocking-attribute). It is used by link types [modulepreload](https://html.spec.whatwg.org/multipage/links.html#link-type-modulepreload), [preload](https://html.spec.whatwg.org/multipage/links.html#link-type-preload) and [stylesheet](https://html.spec.whatwg.org/multipage/links.html#link-type-stylesheet), and it must only be specified on link elements that have a [rel](https://html.spec.whatwg.org/multipage/semantics.html#attr-link-rel) attribute containing one of those keywords.

Am I missing something?

**Comment by NiedziolkaMichal** [comment]
That paragraph in WHATWG seems to be a mistake. I have created issue [#8550](https://github.com/whatwg/html/issues/8550) and then PR [#8621](https://github.com/whatwg/html/pull/8621) to address it.
I created this PR, which changes the validator, immediately after making the PR to the spec because I thought it would be merged quickly. Feel free to postpone merging this PR, until [#8621](https://github.com/whatwg/html/pull/8621) is merged.

**Comment by sideshowbarker** [comment]
> That paragraph in WHATWG seems to be a mistake. I have created issue [#8550](https://github.com/whatwg/html/issues/8550) and then PR [#8621](https://github.com/whatwg/html/pull/8621) to address it.

Ah, OK — thanks, I see now

> Feel free to postpone merging this PR, until https://github.com/whatwg/html/pull/8621 is merged.

Yeah, let’s wait til the spec change is actually made

**Comment by NiedziolkaMichal** [comment]
@sideshowbarker Specification has been changed

**Review by sideshowbarker — APPROVED** [review]

**Pull request merged**
