### PR TITLE
Add support Appveyor (Windows CI service)

### PR DESCRIPTION
**Pull request by takenspc**
Building and running Nu Html Checker on Windows is sometimes broken. To reduce such breakages, I would like to propose using [Appveyor (Windows CI service)](https://www.appveyor.com/).

In this PR, 

- Fix build and test breakages on Windows
    - Use portable day format ('%d') in build/build.py
    - Add support [certifi](https://pypi.python.org/pypi/certifi) to support Let's Encrypt certifications of whatwg.org in build/build.py
    - Use temporary file in `build/build.py check` instead of `echo`
    - Normalize path separator in nu.validator.client.TestRunner
- Port major parts of .travis.yml to appveyor.yml which is .travis.yml equivalent in Appveyor

Build status of appveyor  is here
https://ci.appveyor.com/project/takenspc/validator/

The appveyor.yml in this PR doesn't include

- some parts of tests which are hard to execute on Windows
- Webhook settings (they should be configured after merge)

Webhook settings are documented in below page
https://www.appveyor.com/docs/appveyor-yml/

### CODE REVIEW

**Comment by sideshowbarker** [comment]
Thanks—this looks great and I’m looking forward to landing it.

But for now, it seems like there’s a travis failure that needs to be addressed:

https://travis-ci.org/validator/validator/builds/155531000

> `TypeError: urlopen() got an unexpected keyword argument 'cafile'`

**Comment by takenspc** [comment]
> TypeError: urlopen() got an unexpected keyword argument 'cafile'

This change was introduced in Python 2.7.9 however Travis-CI (ubuntu 12.04 )uses [Python 2.7.3](http://packages.ubuntu.com/precise/python).

Thus change .travis.yml to install Python 2.7.12 manually
https://www.python.org/downloads/release/python-279/
https://docs.python.org/2/library/urllib2.html

**Comment by sideshowbarker** [comment]
>> TypeError: urlopen() got an unexpected keyword argument 'cafile'

> This change was introduced in Python 2.7.9 however Travis-CI (ubuntu 12.04 )uses [Python 2.7.3](http://packages.ubuntu.com/precise/python).
> Thus change .travis.yml to install Python 2.7.12 manually

Cool, yeah, I have run into problems in other projects related to the Ubuntu and Debian stable versions of Python being so old.

**Comment by sideshowbarker** [comment]
https://ci.appveyor.com/project/sideshowbarker/validator/history now set up

I renamed `appveyor.yml` to `.appveyor.yml` (because that’s really how it should be by default…)

> The appveyor.yml in this PR doesn't include Webhook settings (they should be configured after merge)

What webhook settings should be configured?

**Comment by sideshowbarker** [comment]
The TestRunner changes in this PR appear to have broken the behavior of TestRunner when invoked from the jar file and run from the same directory the `messages.json` file is in; e.g.:

    cd tests && java -cp ../build/dist/vnu.jar nu.validator.client.TestRunner messages.json

…causes:

```
2016-09-09 17:50:40.510:INFO::main: Logging initialized @140ms
Exception in thread "main" java.lang.NullPointerException
	at nu.validator.client.TestRunner.runTestSuite(TestRunner.java:467)
	at nu.validator.client.TestRunner.main(TestRunner.java:610)
```

Why?

**Comment by takenspc** [comment]
@sideshowbarker 

> The TestRunner changes in this PR appear to have broken the behavior of TestRunner when invoked from the jar file and run from the same directory the messages.json file is in; e.g.:

Sorry. It is my mistake. I opened new PR which fixes that: https://github.com/validator/validator/pull/352.

**Pull request merged**
