### PR TITLE
More tiny refactors

### PR DESCRIPTION
**Pull request by rwhogg**
Not much here that's too exciting, but I guess that's just a sign of a good clean codebase.

### CODE REVIEW

**Comment by sideshowbarker** [comment]
Keep ’em coming. I tried running PMD myself but even the “basic” ruleset returns a lot of noise. It’d be nice to try to put together a common ruleset we could agree on. But I’d definitely want @hsivonen to weigh in.

**Comment by sideshowbarker** [comment]
btw, e.g., what PMD rule looks for unnecessary `final`? or for use of double quotes around single characters (where using single quotes would be best practice and more performant).

**Comment by rwhogg** [comment]
No kidding about the noise. The one that annoys me the most is the "unnecessary parentheses" rule.

http://pmd.sourceforge.net/pmd-5.2.3/pmd-java/rules/java/strings.html#UseIndexOfChar is what I've been using to find double quotes around single characters - it's only for indexOf() though, not a general check.

http://pmd.sourceforge.net/pmd-5.2.3/pmd-java/rules/java/unnecessary.html#UnnecessaryFinalModifier checks for unnecessary finals inside of an already final class.

**Comment by sideshowbarker** [comment]
ah ok, thanks for the pointers

**Pull request merged**
