### PR TITLE
Make some HTTP-related parameters configurable

### LINKED ISSUE #73: Make HTTP MaxConnPerRoute, MaxConnTotal, MaxRedirects configurable
In [PrudentHttpEntityResolver](https://github.com/validator/validator/blob/master/src/nu/validator/xml/PrudentHttpEntityResolver.java) we hardcode these values:
- MaxConnPerRoute: 100
- MaxTotalConnections: 200
- MaxRedirects: 20＊

Note that [Sensible Defaults for Apache HttpClient ](http://dev.bizo.com/2013/04/sensible-defaults-for-apache-httpclient.html) also recommends those same MaxConnPerRoute and MaxTotalConnections values, and says [Apache HTTP Compenents’ “Fluent API”](http://hc.apache.org/httpcomponents-client-ga/tutorial/html/fluent.html) uses those defaults too.

However, while those values seem sensible, it's conceivable that some people might want to be able to tune them for their checker deployments. So we should expose Java system properties for doing that.

＊MaxConnPerRoute is set in [VerifierServlet.java](https://github.com/validator/validator/blob/master/src/nu/validator/servlet/VerifierServlet.java), then passed from there to PrudentHttpEntityResolver.

### PR DESCRIPTION
**Pull request by xfq**
Fixes #73.

I'm not familiar with the codebase, and I might be missing something. So if I made any mistakes, please point them out. Thanks!

### CODE REVIEW

**Comment by xfq** [comment]
Oops, I forgot to add the "Signed-off-by" line...

**Comment by sideshowbarker** [comment]
> Oops, I forgot to add the "Signed-off-by" line...

You can add that by doing `git commit --amend` and then force-pushing to your remote to get the PR updated with it

**Comment by xfq** [comment]
Done. Thanks!

**Comment by sideshowbarker** [comment]
Thanks much!

**Comment by xfq** [comment]
I didn't add documentation for them, because I'm unsure about my understanding of the technical details of these parameters.

**Comment by sideshowbarker** [comment]
> I didn't add documentation for them, because I'm unsure about my understanding of the technical details of these parameters. 

I’m not that clear on the details of them either—mostly all I know is that they ultimately just get passed on to `org.apache.http.client.HttpClient` do something with

**Pull request merged**
