### PR TITLE
Validate X-UA-Compatible HTTP header

### PR DESCRIPTION
**Pull request by zcorpan**
Fixes https://bugzilla.validator.nu/show_bug.cgi?id=1015

Totally untested. :-)

### CODE REVIEW

**Comment by zcorpan** [comment]
The others in this file were `.fatalError` so I assumed that's how it's done.

**Comment by sideshowbarker** [comment]
> The others in this file were .fatalError so I assumed that's how it's done.

Oh, I guess it must be then

**Comment by hsivonen** [comment]
Looks. Resonable to me (with the follow-up changeset). (I'm shy to click the merge button,because I'm traveling and may not be able follow up if something goes wrong.)

**Comment by sideshowbarker** [comment]
@zcorpan when you have a minute can you please visit https://www.clahub.com/agreements/validator/validator to sign off on the project CLA

**Comment by zcorpan** [comment]
@sideshowbarker done

**Pull request merged**
