### PR TITLE
Sync "Build instructions" of README.md and index.html

### PR DESCRIPTION
**Pull request by takenspc**
Tweak README.md and index.html to reduce differences between the html prewview of README.md and index.html.

This commit doesn't include any content changes.

### CODE REVIEW

**Comment by sideshowbarker** [comment]
The README.md file is an auto-generated file—generated from the index.html file as its source, using the makefile at https://github.com/validator/validator/blob/master/site/Makefile

**Comment by sideshowbarker** [comment]
So, is the README.md in this PR the result of running make with https://github.com/validator/validator/blob/master/site/Makefile with the index.html in this PR as the source? Or did you manually make any edits to the README.md file?

**Comment by takenspc** [comment]
> The README.md file is an auto-generated file

Thank you for your comment. I didn't noticed that. In this PR, I manually edited README.md and index.html. I would like to close this PR not to break README.md and index.html.

**Comment by sideshowbarker** [comment]
> Thank you for your comment. I didn't noticed that. In this PR, I manually edited README.md and index.html. I would like to close this PR not to break README.md and index.html.

Well, it’s fine to submit PRs with changes to the index.html file (even if it's just to get different formatting in the README.md output)

**Pull request closed without merging**
